apiVersion: v1
kind: Namespace
metadata:
  name: sales-api-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-pod # Base POD name
  namespace: sales-api-system
spec:
  selector:
    matchLabels:
      app: sales-api # Selector for POD name search.
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: sales-api-api
        image: sales-api-image