apiVersion: v1
kind: Namespace
metadata:
  name: sales-api-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-pod # Base POD name
  namespace: sales-api-system
spec:
  selector:
    matchLabels:
      app: sales-api # Selector for POD name search.
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
      - name: init-migrate
        image: sales-api-image
        command: ['./sales-admin', 'migrate']
      - name: init-seed
        image: sales-api-image
        command: ['./sales-admin', 'seed']
      containers:
      - name: sales-api
        image: sales-api-image
        ports: 
        - name: sales-api
          containerPort: 9020
        - name: sales-api-debug
          containerPort: 9021
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /debug/readiness
            port: 9021
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness
            port: 9021
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-api-system
spec:
  type: ClusterIP
  selector:
    app: sales-api
  ports:
  - name: sales-api
    port: 9020
    targetPort: sales-api
  - name: sales-api-debug
    port: 9021
    targetPort: sales-api-debug