apiVersion: v1
kind: Namespace
metadata:
  name: sales-api-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api-pod # Base POD name
  namespace: sales-api-system
spec:
  selector:
    matchLabels:
      app: sales-api # Selector for POD name search.
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: sales-api
        image: sales-api-image
        ports: 
        - name: sales-api
          containerPort: 9020
        - name: sales-api-debug
          containerPort: 9021
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-api-system
spec:
  type: ClusterIP
  selector:
    app: sales-api
  ports:
  - name: sales-api
    port: 9020
    targetPort: sales-api
  - name: sales-api-debug
    port: 9021
    targetPort: sales-api-debug