FROM golang:1.17 as buid_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service

WORKDIR /service/app/services/sales-api
RUN go build -ldflags "-X main.buid=${BUILD_REF}" -o sales-api

FROM alpine:3.16
ARG BUILD_REF
RUN addgroup -g 1000 -S sales-api && \
    adduser -u 1000 -h /service -G sales-api -S sales-api
COPY --from=buid_sales-api --chown=sales-api:sales-api /service/app/services/sales-api/sales-api /service/sales-api
WORKDIR /service
USER sales-api
CMD ["./sales-api"]